// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLG2DMn1eS1aVG7ZMtD2yitkD1ZdTmRD8',
    appId: '1:221525248711:web:ca852437546bec46e54ce2',
    messagingSenderId: '221525248711',
    projectId: 'self-a0cc9',
    authDomain: 'self-a0cc9.firebaseapp.com',
    storageBucket: 'self-a0cc9.appspot.com',
    measurementId: 'G-2PVLKM8K87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgEzm2GriO20JTBpAXnJTT6YypYKjzx4',
    appId: '1:221525248711:android:eebf03d3c392abb7e54ce2',
    messagingSenderId: '221525248711',
    projectId: 'self-a0cc9',
    storageBucket: 'self-a0cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBt53XvjH15YbQi1BbCuN9sTzzL8EX86k',
    appId: '1:221525248711:ios:35c58d3fb3de0ff0e54ce2',
    messagingSenderId: '221525248711',
    projectId: 'self-a0cc9',
    storageBucket: 'self-a0cc9.appspot.com',
    iosClientId: '221525248711-mhpbqe4387blhgsagspp78ino4bp13kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.klontong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBt53XvjH15YbQi1BbCuN9sTzzL8EX86k',
    appId: '1:221525248711:ios:35c58d3fb3de0ff0e54ce2',
    messagingSenderId: '221525248711',
    projectId: 'self-a0cc9',
    storageBucket: 'self-a0cc9.appspot.com',
    iosClientId: '221525248711-mhpbqe4387blhgsagspp78ino4bp13kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.klontong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLG2DMn1eS1aVG7ZMtD2yitkD1ZdTmRD8',
    appId: '1:221525248711:web:fbfa712fa5c55aa7e54ce2',
    messagingSenderId: '221525248711',
    projectId: 'self-a0cc9',
    authDomain: 'self-a0cc9.firebaseapp.com',
    storageBucket: 'self-a0cc9.appspot.com',
    measurementId: 'G-JVLPQ1VH8G',
  );
}
